name: Run auto-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'


    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Build with Gradle Wrapper
      run: ./gradle test --tests src.test.java.ReqResTest


    - name: ls
      run: ls -lah

