name: Run auto-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '17'
    #     distribution: 'temurin'


    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.4

    - name: help
      run: gradle -h
    - name: Version
      run: gradle -v

    - name: Build with Gradle Wrapper
      run: gradle test 

    - name: ls
      run: ls -lah
    - name: ls
      run: |
        ls -lah build
        echo "=============Reports============="
        ls -lah build/reports/tests/test
        echo "=============test-results============="
        cat -lah build/test-results/test/*.xml


